### Homework 1
link to homework...

https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/course-zoomcamp/01-intro/homework.md

In [91]:
import pandas as pd
import numpy as np

#### Question 1 & Question 2

In [92]:
print(f"Current pandas version: {pd.__version__}")
print(f"Current numpy version: {np.__version__}")


Current pandas version: 1.4.3
Current numpy version: 1.21.5


In [93]:
data = pd.read_csv("01_homework.csv")

In [94]:
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

#### Question 3

In [95]:
data[data['Make'] == "BMW"]['MSRP'].mean()

61546.76347305389

#### Question 4

In [96]:
data_2015 = data[data.Year >= 2015]

#### Question 5

In [97]:
data_2015['Engine HP'].isna().sum()

51

In [98]:
mean_before = round(data_2015['Engine HP'].mean())

In [99]:
data_2015_filled = data_2015
data_2015_filled['Engine HP'].fillna(mean_before, inplace=True)
data_2015_filled['Engine HP'].isna().sum()

C:\Users\levan\AppData\Local\Temp\ipykernel_5832\2642742851.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_2015_filled['Engine HP'].fillna(mean_before, inplace=True)


0

In [100]:
mean_after = round(data_2015_filled["Engine HP"].mean())
print(f"Mean before filling the missing values: {mean_before}")
print(f"Mean after filling the missing values: {mean_after}")

Mean before filling the missing values: 273
Mean after filling the missing values: 273


#### Question 6

In [101]:
data_rolls_royce = data[data['Make'] == 'Rolls-Royce']

X = data_rolls_royce[["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates()

X
X.shape

(7, 3)

In [102]:
XT = X.T
XT
XT.shape

(3, 7)

In [103]:
XTX = np.dot(X.T,X)
print(XTX)

XTX_i = np.linalg.inv(XTX)
print(XTX_i)
XTX_i.sum()

[[1.754801e+06 3.965600e+04 6.519600e+04]
 [3.965600e+04 9.280000e+02 1.500000e+03]
 [6.519600e+04 1.500000e+03 2.454000e+03]]
[[ 5.17815728e-05  9.06587044e-04 -1.92984188e-03]
 [ 9.06587044e-04  1.05723058e-01 -8.87084092e-02]
 [-1.92984188e-03 -8.87084092e-02  1.05900809e-01]]


0.032212320677486195

#### Questions 7

In [104]:
Y = [1000, 1100, 900, 1200, 1000, 850, 1300]
w = np.dot(np.dot(XTX_i, XT),Y)
print(w)

[ 0.19989598 31.02612262 31.65378877]
